name: Deploy

on:
  push:
    branches: [main]
    paths:  # Only trigger when these paths change
      - 'app/**'
      - 'kubernetes/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sre-demo-dev-ecr-api
  EKS_CLUSTER: sre-demo-dev-eks-cluster
  AWS_ACCOUNT_ID: 502274764708

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python 3.12
        uses: actions/setup-python@v5 
        with:
          python-version: "3.12"

      - name: Run tests
        run: | 
          cd app
          pip install -r requirements.txt
          python -m pytest tests/ -v 

      - name: Configure AWS credentials (Removed OIDC)
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/sre-demo-api \
            sre-demo-api=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -n sre-demo

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/sre-demo-api \
            -n sre-demo \
            --timeout=120s

      - name: Smoke test
        run: |
          LB=$(kubectl get svc sre-demo-api -n sre-demo \
            -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "Testing $LB"
          sleep 10
          curl -f http://${LB}/api/health